# 数据清洗和准备

## 处理缺失数据

In [2]:
import numpy as np
import pandas as pd

In [3]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [5]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [6]:
string_data[0]=None
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [7]:
from numpy import nan as NA
data = pd.Series([1, NA, 3.5, NA, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [8]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [9]:
#dataframe默认丢弃含有NA的行和列
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
[NA, NA, NA], [NA, 6.5, 3.]])
cleaned = data.dropna()
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [10]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [11]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [12]:
data[4]=NA
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [13]:
data.dropna(axis=1,how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [14]:
 df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA
df

0         1         2
0 -0.828921       NaN       NaN
1  1.682938       NaN       NaN
2  0.833117       NaN  1.051677
3 -1.049164       NaN  1.323003
4 -1.355522  0.351217  1.204617
5  0.945299  0.728405  0.270412
6 -1.767389  1.254684  0.809052

In [15]:
df.dropna()

0         1         2
4 -1.355522  0.351217  1.204617
5  0.945299  0.728405  0.270412
6 -1.767389  1.254684  0.809052

In [16]:
df.dropna(thresh=2)   #删掉含有两个NA的行

0         1         2
2  0.833117       NaN  1.051677
3 -1.049164       NaN  1.323003
4 -1.355522  0.351217  1.204617
5  0.945299  0.728405  0.270412
6 -1.767389  1.254684  0.809052

In [17]:
df.fillna(0)

0         1         2
0 -0.828921  0.000000  0.000000
1  1.682938  0.000000  0.000000
2  0.833117  0.000000  1.051677
3 -1.049164  0.000000  1.323003
4 -1.355522  0.351217  1.204617
5  0.945299  0.728405  0.270412
6 -1.767389  1.254684  0.809052

In [18]:
#调用字典对不同列进行填充
df.fillna({1:0.5,2:0})

0         1         2
0 -0.828921  0.500000  0.000000
1  1.682938  0.500000  0.000000
2  0.833117  0.500000  1.051677
3 -1.049164  0.500000  1.323003
4 -1.355522  0.351217  1.204617
5  0.945299  0.728405  0.270412
6 -1.767389  1.254684  0.809052

In [19]:
_=df.fillna(0,inplace=True)
df

0         1         2
0 -0.828921  0.000000  0.000000
1  1.682938  0.000000  0.000000
2  0.833117  0.000000  1.051677
3 -1.049164  0.000000  1.323003
4 -1.355522  0.351217  1.204617
5  0.945299  0.728405  0.270412
6 -1.767389  1.254684  0.809052

In [20]:
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[2:, 1] = NA
df.iloc[4:, 2] = NA
df

0         1         2
0  0.292859 -0.300711 -1.136522
1  0.654879 -0.634633 -0.009853
2  1.852705       NaN  0.188445
3  1.385226       NaN -1.136567
4  1.113135       NaN       NaN
5  0.839360       NaN       NaN

In [22]:
df.fillna(method='ffill',limit=2)

0         1         2
0  0.292859 -0.300711 -1.136522
1  0.654879 -0.634633 -0.009853
2  1.852705 -0.634633  0.188445
3  1.385226 -0.634633 -1.136567
4  1.113135       NaN -1.136567
5  0.839360       NaN -1.136567

In [23]:
data = pd.Series([1., NA, 3.5, NA, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

## 数据转换

In [25]:
#移除重复数据
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [26]:
data.duplicated()       #是否与前面行重复

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [27]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [29]:
data['v1'] = range(7)
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [30]:
data.drop_duplicates(['k1', 'k2'], keep='last') #keep参数默认为first

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [31]:
#利用函数或映射进行数据转换
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
 'Pastrami', 'corned beef', 'Bacon',
 'pastrami', 'honey ham', 'nova lox'],
 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [32]:
meat_to_animal = {
'bacon': 'pig',
'pulled pork': 'pig',
'pastrami': 'cow',
'corned beef': 'cow',
'honey ham': 'pig',
'nova lox': 'salmon'
}

In [33]:
lowercased=data['food'].str.lower()
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [34]:
data['animal']=lowercased.map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [35]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [37]:
#替换值
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [39]:
data.replace([-999,-1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [40]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [41]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [48]:
# 重命名轴索引
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
index=['Ohio', 'Colorado', 'New York'],
columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [50]:
transform = lambda x: x[:3].upper()
data.index=data.index.map(transform)
data

one  two  three  four
OHI    0    1      2     3
COL    4    5      6     7
NEW    8    9     10    11

In [51]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohi    0    1      2     3
Col    4    5      6     7
New    8    9     10    11

In [54]:
data.rename(index={'OHI': 'INDIANA'},
columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COL        4    5         6     7
NEW        8    9        10    11

In [55]:
data.rename(index={'OHI': 'INDIANA'}, inplace=True)
data

one  two  three  four
INDIANA    0    1      2     3
COL        4    5      6     7
NEW        8    9     10    11

In [56]:
#离散化和面元划分
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [58]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [59]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]]
              closed='right',
              dtype='interval[int64]')

In [61]:
pd.value_counts(cats)     #面元计数

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [62]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [64]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages,bins,labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [65]:
data = np.random.rand(20)
data

array([0.0689543 , 0.94179171, 0.12564171, 0.43237767, 0.61089118,
       0.97355004, 0.02013343, 0.82233356, 0.14408255, 0.52862054,
       0.10613697, 0.47904138, 0.90870725, 0.07774092, 0.49856898,
       0.76825479, 0.57506013, 0.18695363, 0.9921484 , 0.79797064])

In [66]:
pd.cut(data, 4, precision=2)    #传入数量，等长划分，小数位数为2

[(0.019, 0.26], (0.75, 0.99], (0.019, 0.26], (0.26, 0.51], (0.51, 0.75], ..., (0.75, 0.99], (0.51, 0.75], (0.019, 0.26], (0.75, 0.99], (0.75, 0.99]]
Length: 20
Categories (4, interval[float64]): [(0.019, 0.26] < (0.26, 0.51] < (0.51, 0.75] < (0.75, 0.99]]

In [67]:
data = np.random.randn(1000) # Normally distributed
cats = pd.qcut(data, 4) # Cut into quartiles   根据样本分位数对数据进⾏⾯元划分
cats

[(-2.984, -0.652], (-2.984, -0.652], (-0.652, 0.00542], (-2.984, -0.652], (0.714, 2.89], ..., (-0.652, 0.00542], (0.714, 2.89], (-2.984, -0.652], (0.714, 2.89], (0.00542, 0.714]]
Length: 1000
Categories (4, interval[float64]): [(-2.984, -0.652] < (-0.652, 0.00542] < (0.00542, 0.714] < (0.714, 2.89]]

In [68]:
pd.value_counts(cats)

(0.714, 2.89]        250
(0.00542, 0.714]     250
(-0.652, 0.00542]    250
(-2.984, -0.652]     250
dtype: int64

In [69]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(-1.249, 0.00542], (-1.249, 0.00542], (-1.249, 0.00542], (-2.984, -1.249], (1.312, 2.89], ..., (-1.249, 0.00542], (0.00542, 1.312], (-1.249, 0.00542], (1.312, 2.89], (0.00542, 1.312]]
Length: 1000
Categories (4, interval[float64]): [(-2.984, -1.249] < (-1.249, 0.00542] < (0.00542, 1.312] < (1.312, 2.89]]

In [70]:
#检测和过滤异常值
data = pd.DataFrame(np.random.randn(1000, 4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.040243    -0.022513     0.116359    -0.019057
std       0.994371     0.976387     1.030010     1.021537
min      -3.699983    -2.837387    -3.448605    -3.352552
25%      -0.647815    -0.640214    -0.566322    -0.730495
50%       0.047346    -0.042551     0.110797    -0.064899
75%       0.728544     0.577984     0.814904     0.664061
max       2.924110     4.298548     2.907834     3.855801

In [71]:
col=data[2]

In [72]:
col[np.abs(col)>3]

219   -3.448605
Name: 2, dtype: float64

In [73]:
 data[(np.abs(data) > 3).any(1)]

0         1         2         3
44   0.532962  4.298548 -0.562905 -0.795224
107 -2.125893  0.600707 -0.921466 -3.352552
219 -0.079706  0.482640 -3.448605 -0.272909
220  0.103582  2.408765  2.554073 -3.043628
260  1.335267  3.131786 -1.577753  0.396324
345 -0.306713  3.563674 -0.806729 -0.721556
487 -0.448611 -0.739353  1.395069  3.112181
490 -0.803924  3.210447  0.242644  0.820762
522  0.003088 -0.186528 -0.459579  3.855801
623  1.599949  1.048150 -0.387626  3.680636
733  0.144675  3.305884  0.541873 -0.367617
748 -3.018636 -0.298212 -0.103554 -0.808804
762 -1.398405  3.097537  1.289062  0.840029
881 -3.699983 -0.768508 -0.474903  0.849336

In [74]:
data[np.abs(data) > 3] = np.sign(data) * 3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.040962    -0.025121     0.116808    -0.020310
std       0.991922     0.967147     1.028553     1.014826
min      -3.000000    -2.837387    -3.000000    -3.000000
25%      -0.647815    -0.640214    -0.566322    -0.730495
50%       0.047346    -0.042551     0.110797    -0.064899
75%       0.728544     0.577984     0.814904     0.664061
max       2.924110     3.000000     2.907834     3.000000

In [75]:
np.sign(data).head()

0    1    2    3
0 -1.0  1.0 -1.0 -1.0
1  1.0 -1.0 -1.0 -1.0
2 -1.0  1.0  1.0  1.0
3  1.0 -1.0  1.0 -1.0
4 -1.0 -1.0  1.0  1.0

In [77]:
#排列和随机采样
#利⽤numpy.random.permutation函数可以轻松实现对Series或DataFrame的列的排列⼯作（permuting，随机重排序）
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))
sampler = np.random.permutation(5)
sampler

array([3, 1, 0, 2, 4])

In [78]:
df.take(sampler)

0   1   2   3
3  12  13  14  15
1   4   5   6   7
0   0   1   2   3
2   8   9  10  11
4  16  17  18  19

In [79]:
df.sample(n=3)

0   1   2   3
2   8   9  10  11
1   4   5   6   7
3  12  13  14  15

In [80]:
choices = pd.Series([5, 7, -1, 6, 4])
draws = choices.sample(n=10, replace=True)
draws

1    7
0    5
3    6
0    5
0    5
1    7
2   -1
3    6
1    7
3    6
dtype: int64

In [81]:
choices

0    5
1    7
2   -1
3    6
4    4
dtype: int64

In [82]:
#计算指标、哑变量
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
 'data1': range(6)})
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [86]:
dummies= pd.get_dummies(df['key'],prefix='key')

In [87]:
df_with_dummy=df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [88]:
mnames = ['movie_id', 'title', 'genres']
movies = pd.read_table('movies.dat', sep='::',header=None, names=mnames)
movies[:10]

d:\python3.6\lib\site-packages\ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  


movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [90]:
movies.genres

0          Animation|Children's|Comedy
1         Adventure|Children's|Fantasy
2                       Comedy|Romance
3                         Comedy|Drama
4                               Comedy
5                Action|Crime|Thriller
6                       Comedy|Romance
7                 Adventure|Children's
8                               Action
9            Action|Adventure|Thriller
10                Comedy|Drama|Romance
11                       Comedy|Horror
12                Animation|Children's
13                               Drama
14            Action|Adventure|Romance
15                      Drama|Thriller
16                       Drama|Romance
17                            Thriller
18                              Comedy
19                              Action
20                 Action|Comedy|Drama
21                Crime|Drama|Thriller
22                            Thriller
23                        Drama|Sci-Fi
24                       Drama|Romance
25                       

In [91]:
all_genres=[]
for x in movies.genres:
    all_genres.extend(x.split('|'))
genres=pd.unique(all_genres)
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [92]:
zero_matrix = np.zeros((len(movies), len(genres)))
dummies=pd.DataFrame(zero_matrix,columns=genres)

In [93]:
gen = movies.genres[0]
gen.split('|')

['Animation', "Children's", 'Comedy']

In [94]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2], dtype=int64)

In [95]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1

In [96]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [97]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Adventure                                0
Genre_Fantasy                                  0
Genre_Romance                                  0
Genre_Drama                                    0
Genre_Action                                   0
Genre_Crime                                    0
Genre_Thriller                                 0
Genre_Horror                                   0
Genre_Sci-Fi                                   0
Genre_Documentary                              0
Genre_War                                      0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Film-Noir                                0
Genre_Western       

In [99]:
np.random.seed(12345)
values = np.random.rand(10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [100]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

## 字符串操作